### ISSUE TITLE
[Question] dailynotes configuration

### ISSUE THREAD

**Issue by duchenpaul** [djedi/DailyNotes#32]
1. Set up DATABASE_URI,
How to set up database, I tried to use below config to set up mysql database, but it still creates itself a sqlite.
```yaml
version: "2"
services:
  dailynotes:
    image: m0ngr31/dailynotes:version-1.0-beta6
    container_name: dailynotes
    volumes:
      - {{ dailynotes_data_dir }}:/app/config
    environment:
      - DB_SERVER_HOST=mysql://pi:test@192.168.2.214/dailynotes
    ports:
      - {{ http_port }}:5000
    restart: always
```

2. Example for `/app/config`, could you please give us some examples about the config, is config a file or a dir?
3. Does it need database drives to install to use mysql? what if I would like to use pgsql, do I need to pip install psycopg2, and how? Just like `docker exec dailynote pip install psycopg2`?
