### ISSUE TITLE
Can't save any entry: "There was an error saving. Please try again."

### ISSUE THREAD

**Issue by glennrice** [djedi/DailyNotes#36]
I just came across this and wanted to give it a go but can't seem to get it to save any notes. 

I even tried setting the /app/config folder and the app.db to 777 but still get the same message pop up in the web interface whenever I click the save icon.

Apart from that the docker image appears to be running fine and I can create a user and login fine.

Is there something I've missed? Or even a log file somewhere on the docker that I have missed?

**Comment by 174n** [comment]
I have the same problem. I'm using docker on arch linux and this docker-compose:
```yml
services: 
  server:
    image: m0ngr31/dailynotes
    ports:
      - 5000:5000
    volumes:
      - ./volume:/app/config
    environment: 
      API_SECRET_KEY: asdfsadfsadf
      DB_ENCRYPTION_KEY: asdfasdfasdf
```
